version: 2.1

jobs:
  test:
    docker:
      - image: ramongarver/muii-ccfi:latest
    steps:
      - checkout
      - name: Running tests
      - run:
          command: | 
            cd api
            pnpm install-test

workflows:
  full-test:
    jobs:
      - test
