name: Run API tests

on:
  workflow_run:
    workflows: ["Create and publish a Docker image to GitHub Container Registry"]
    branches: [main]
    types: [completed]

jobs:
  run_test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run:
          docker run -t -v `pwd`:/app/test ramongarver/muii-ccfi
